const data = [
    {
        id: 1,
        mainImage: '/images/product/product-1-1.jpg',
        hoverImage: '/images/product/product-1-2.jpg',
        author: 'armani',
        name: 'Seeds of Change Organic Quinoa, Brown',
        star: '80%',
        by: 'NestFood',
        newPrice: '238.25',
        oldPrice: '245.8',
        hot: true,
        sale: true,
        discount: '20%',
        new: true,
        total: 150,
        remain: 40
    },
    {
        id: 2,
        mainImage: '/images/product/product-2-1.jpg',
        hoverImage: '/images/product/product-2-2.jpg',
        author: 'armani',
        name: 'All Natural Italian-Style Chicken Meatballs',
        star: '90%',
        by: 'NestFood',
        newPrice: '238.25',
        oldPrice: '245.8',
        new: true,
        hot: true,
        sale: true,
        total: 150,
        remain: 40
    },
    {
        id: 3,
        mainImage: '/images/product/product-3-1.jpg',
        hoverImage: '/images/product/product-3-2.jpg',
        author: 'armani',
        name: 'All Natural Italian-Style Chicken Meatballs',
        star: '90%',
        by: 'NestFood',
        newPrice: '238.25',
        oldPrice: '245.8',
        new: true,
        hot: true,
        discount: '14%',
        total: 150,
        remain: 40
    },
    {
        id: 4,
        mainImage: '/images/product/product-4-1.jpg',
        hoverImage: '/images/product/product-4-2.jpg',
        author: 'armani',
        name: 'All Natural Italian-Style Chicken Meatballs',
        star: '90%',
        by: 'NestFood',
        newPrice: '238.25',
        oldPrice: '245.8',
        hot: true,
        sale: true,
        total: 150,
        remain: 40
    },
    {
        id: 5,
        mainImage: '/images/product/product-5-1.jpg',
        hoverImage: '/images/product/product-5-2.jpg',
        author: 'armani',
        name: 'All Natural Italian-Style Chicken Meatballs',
        star: '90%',
        by: 'NestFood',
        newPrice: '238.25',
        oldPrice: '245.8',
        new: true,
        total: 150,
        remain: 40
    },
    {
        id: 6,
        mainImage: '/images/product/product-6-1.jpg',
        hoverImage: '/images/product/product-6-2.jpg',
        author: 'armani',
        name: 'All Natural Italian-Style Chicken Meatballs',
        star: '90%',
        by: 'NestFood',
        newPrice: '238.25',
        oldPrice: '245.8',
        hot: true,
        sale: true,
        total: 150,
        remain: 40
    },
    {
        id: 7,
        mainImage: '/images/product/product-7-1.jpg',
        hoverImage: '/images/product/product-7-2.jpg',
        author: 'armani',
        name: 'All Natural Italian-Style Chicken Meatballs',
        star: '90%',
        by: 'NestFood',
        newPrice: '238.25',
        oldPrice: '245.8',
        new: true,
        total: 150,
        remain: 40
    },
    {
        id: 8,
        mainImage: '/images/product/product-8-1.jpg',
        hoverImage: '/images/product/product-8-2.jpg',
        author: 'armani',
        name: 'All Natural Italian-Style Chicken Meatballs',
        star: '90%',
        by: 'NestFood',
        newPrice: '238.25',
        oldPrice: '245.8',
        new: true,
        total: 150,
        remain: 40
    },
    {
        id: 9,
        mainImage: '/images/product/product-9-1.jpg',
        hoverImage: '/images/product/product-9-2.jpg',
        author: 'armani',
        name: 'All Natural Italian-Style Chicken Meatballs',
        star: '90%',
        by: 'NestFood',
        newPrice: '238.25',
        oldPrice: '245.8',
        sale: true,
        discount: '40%',
        total: 150,
        remain: 40
    },
    {
        id: 10,
        mainImage: '/images/product/product-10-1.jpg',
        hoverImage: '/images/product/product-10-2.jpg',
        author: 'armani',
        name: 'All Natural Italian-Style Chicken Meatballs',
        star: '90%',
        by: 'NestFood',
        newPrice: '238.25',
        oldPrice: '245.8',
        new: true,
        discount: '49%',
        hot: true,
        total: 150,
        remain: 40
    },
]
export default data