export { default as AboutUs } from './About-us/AboutUs'
export { default as Home } from './Home/Home'
export { default as Blog } from './Blog/Blog'
export { default as DetailBlog } from './Blog/DetailBlog/DetailBlog'
export { default as Shop } from './Shop/Shop'
export { default as Settings } from './Settings/Settings'
export { default as ThankYou } from './ThankYou/ThankYou'
export { default as MyVoucher } from './MyAccount/MyVoucher/MyVoucher'
export { default as MyAccount } from './MyAccount/MyAccount'
export { default as OrderTracking } from './OrderTracking/OrderTracking'
export { default as LoginBuy } from './Buyer/LoginBuy/LoginBuy'
export { default as RegisterBuy } from './Buyer/RegisterBuy/RegisterBuy'
export { default as LoginSell } from './Seller/LoginSell/LoginSell'
export { default as RegisterSell } from './Seller/RegisterSell/RegisterSell'
export { default as Contact } from './Contact/Contact'
export { default as  Cart} from './Shop/Cart/Cart'
export { default as  CheckOut} from './Shop/CheckOut/CheckOut'
export { default as  Compare} from './Shop/Compare/Compare'
export { default as  WishList} from './Shop/WishList/WishList'
export { default as  Vendor} from './Shop/Vendor/Vendor'
export {default as ProductDetail} from './Product/ProductDetail/ProductDetail'
