export { default as AboutUs } from './About-us/AboutUs'
export { default as Home } from './Home/Home'
export { default as Blog } from './Blog/Blog'
export { default as DetailBlog } from './Blog/DetailBlog/DetailBlog'
export { default as Shop } from './Shop/Shop'
export { default as PurchaseGuide } from './PurchaseGuide/PurchaseGuide'
export { default as TermService } from './TermService/TermService'
export { default as Privacy } from './Privacy/Privacy'
export { default as NotFound } from './NotFound/NotFound'
export { default as Settings } from './Settings/Settings'
export { default as ThankYou } from './ThankYou/ThankYou'
export { default as MyVoucher } from './MyAccount/MyVoucher/MyVoucher'
export { default as MyAccount } from './MyAccount/MyAccount'
export { default as OrderTracking } from './OrderTracking/OrderTracking'
export { default as LoginBuy } from './Buyer/LoginBuy/LoginBuy'
export { default as RegisterBuy } from './Buyer/RegisterBuy/RegisterBuy'
export { default as LoginSell } from './Seller/LoginSell/LoginSell'
export { default as Customer } from './Seller/Customer/Customer'
export { default as Dashboard } from './Seller/Dashboard/DashBoard'
export { default as AccountDetail } from './Seller/Account/AccountDetail/AccountDetail'
export { default as Account } from './Seller/Account/Account'
export { default as Order } from './Seller/Order/Order'
export { default as Overview } from './Seller/Overview/Overview'
export { default as Products } from './Seller/Products/Products'
export { default as SettingSell } from './Seller/Settings/Settings'
export { default as RegisterSell } from './Seller/RegisterSell/RegisterSell'
export { default as Delivers } from './Seller/Delivers/Delivers'
export { default as Vouchers } from './Seller/Vouchers/Vouchers'
export { default as Contact } from './Contact/Contact'
export { default as  Cart} from './Shop/Cart/Cart'
export { default as  CheckOut} from './Shop/CheckOut/CheckOut'
export { default as  Compare} from './Shop/Compare/Compare'
export { default as  WishList} from './Shop/WishList/WishList'
export { default as  Vendor} from './Shop/Vendor/Vendor'
export { default as  VendorDetail} from './Shop/Vendor/VendorDetail/VendorDetail'
export {default as ProductDetail} from './Product/ProductDetail/ProductDetail'
export {default as HotDeal} from './HotDeal/HotDeal'
